[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install -r requirements-railway.txt"
]

[phases.start]
cmd = "gunicorn 'wsgi:app' --bind 0.0.0.0:$PORT --log-level info --workers 1 --timeout 120"

[variables]
PYTHONPATH = "/app" 